In [15]:
import numpy as np

perch_length = np.array(
    [8.4, 13.7, 15.0, 16.2, 17.4, 18.0, 18.7, 19.0, 19.6, 20.0, 
     21.0, 21.0, 21.0, 21.3, 22.0, 22.0, 22.0, 22.0, 22.0, 22.5, 
     22.5, 22.7, 23.0, 23.5, 24.0, 24.0, 24.6, 25.0, 25.6, 26.5, 
     27.3, 27.5, 27.5, 27.5, 28.0, 28.7, 30.0, 32.8, 34.5, 35.0, 
     36.5, 36.0, 37.0, 37.0, 39.0, 39.0, 39.0, 40.0, 40.0, 40.0, 
     40.0, 42.0, 43.0, 43.0, 43.5, 44.0]
     )
perch_weight = np.array(
    [5.9, 32.0, 40.0, 51.5, 70.0, 100.0, 78.0, 80.0, 85.0, 85.0, 
     110.0, 115.0, 125.0, 130.0, 120.0, 120.0, 130.0, 135.0, 110.0, 
     130.0, 150.0, 145.0, 150.0, 170.0, 225.0, 145.0, 188.0, 180.0, 
     197.0, 218.0, 300.0, 260.0, 265.0, 250.0, 250.0, 300.0, 320.0, 
     514.0, 556.0, 840.0, 685.0, 700.0, 700.0, 690.0, 900.0, 650.0, 
     820.0, 850.0, 900.0, 1015.0, 820.0, 1100.0, 1000.0, 1100.0, 
     1000.0, 1000.0]
     )

In [16]:
# 훈련 세트와 테스트 세트를 2차원 배열로 바꿉니다
train_input = perch_length.reshape(-1, 1)
test_input = perch_weight.reshape(-1, 1)

In [17]:
class gradient_descent:
  n_iterations = 0  # 데이터 개수
  eta = 0.001 # 학습률  
  theta = np.random.randn(2,1) # 가중치 무작위 초기화
  momentum_p = 0.00009
  momentum = 0

  def eta(self, eta):
    self.eta = eta
  
  def gradient(self, x, y):
    x_b = np.c_[x, np.ones((x.shape[0],1))] # 입력 데이터에 편향값을 위한 1의 추가
    self.n_iterations = x.shape[0]
    for iterations in range(self.n_iterations):
      gradients = (2/self.n_iterations) * x_b.T.dot(x_b.dot(self.theta) - y)
      self.theta = self.theta - self.eta * gradients
      print(self.theta, gradients)

    return self.theta

  def gradient_nesterov(self, x, y):
    x_b = np.c_[x, np.ones((x.shape[0],1))] # 입력 데이터에 편향값을 위한 1의 추가
    self.n_iterations = x.shape[0]

    for iterations in range(self.n_iterations):
      if iterations != 0:
        self.momentum = self.momentum + self.momentum_p * gradients
      
      gradients = (2/self.n_iterations) * x_b.T.dot(x_b.dot(self.theta-self.momentum) - y)
      
      self.theta = self.theta - self.eta * gradients - self.momentum

    return self.theta

  def predict(self, x):
    x_b = np.c_[x, np.ones((x.shape[0],1))]
    print(x_b, self.theta)
    return x_b@(self.theta)

In [18]:
gd2 = gradient_descent()
gd2.eta(0.001)
w = gd2.gradient_nesterov(train_input, test_input)

In [19]:
w

array([[ 16.58630584],
       [-22.26318678]])

In [20]:
gd2.theta

array([[ 16.58630584],
       [-22.26318678]])

In [21]:
gd2.momentum

array([[-0.02894401],
       [ 0.58978216]])