In [17]:
import numpy as np

입력층

In [18]:
input_data = np.array([[2,3],[5,1]])

x = input_data.reshape(-1)

In [19]:
x

array([2, 3, 5, 1])

가중치 및 편향

In [20]:
w1 = np.array([2,1,-3,3])
w2 = np.array([1,-3,1,3])
b1 = 3
b2 = 3

가중합

In [21]:
W = np.array([w1,w2])
W

array([[ 2,  1, -3,  3],
       [ 1, -3,  1,  3]])

In [22]:
b = np.array([b1,b2])
b

array([3, 3])

In [23]:
weight_sum = W.dot(x) + b
weight_sum

array([-2,  4])

In [24]:
weight_sum2 = np.dot(W, x) + b
weight_sum2

array([-2,  4])

In [25]:
weight_sum3 = W@x+b
weight_sum3

array([-2,  4])

출력층

In [27]:
res = 1/(1+np.exp(-weight_sum))
res

array([0.11920292, 0.98201379])