In [89]:
import numpy as np

입력, 출력 값의 지정

In [90]:
input = np.array([[1,2,3]])
input.shape

(1, 3)

In [91]:
target = np.array([[0.5,0.1]])
target.shape

(1, 2)

In [92]:
print(input.shape, target.shape)

(1, 3) (1, 2)


임의의 가중치 설정

In [93]:
w1 = np.array([[0.1,0.3,0.5],[0.2,0.4,0.6]])
w1.shape

(2, 3)

In [94]:
w2 = np.array([[0.7,0.9],[0.8,0.1]])
w2.shape

(2, 2)

In [95]:
b1 = np.array([[0.5],[0.5]])
b1.shape

(2, 1)

In [96]:
b2 = np.array([[0.3],[0.3]])
b2.shape

(2, 1)

순전파를 통한 출력값 계산

In [97]:
print(input.shape,w1.shape)

(1, 3) (2, 3)


In [98]:
g1 = w1.dot(input.T)+b1 
g1

array([[2.7],
       [3.3]])

In [99]:
h1 = 1/(1+np.exp(-g1))
h1

array([[0.93702664],
       [0.96442881]])

In [100]:
z1 = w2.dot(h1)+b2
z1

array([[1.82390458],
       [1.1460642 ]])

In [101]:
y1 = 1/(1+np.exp(-z1))
y1

array([[0.86103399],
       [0.75879129]])

역전파 계산, 각 가중치에 대한 비용 함수의 변화량을 계산한다.

In [102]:
c_w2 = y1*(1-y1)*((y1.T-target).T).dot(h1.T)
c_w2

array([[0.04047892, 0.04166268],
       [0.11298352, 0.11628758]])

In [103]:
c_b2 = (y1*(1-y1)).T.dot((y1.T-target).T)
c_b2

array([[0.16377596]])

In [104]:
c_y = y1-target.T
c_y

array([[0.36103399],
       [0.65879129]])

In [105]:
y_z = (y1*(1-y1))
y_z

array([[0.11965446],
       [0.18302707]])

In [106]:
c_h = c_y.T*y_z.T@w2
c_h

array([[0.12670084, 0.05093706]])

In [115]:
h_g = h1*(1-h1)
h_g

array([[0.05900771],
       [0.03430588]])

In [132]:
c_w1 = (c_h*(h_g.T)).T*input
c_w1

array([[0.00747633, 0.01495265, 0.02242898],
       [0.00174744, 0.00349488, 0.00524232]])

In [139]:
c_b1 = c_h.dot(h_g)
c_b1

array([[0.00922377]])