In [28]:
import numpy as np

입력 데이터 생성

In [29]:
input = np.random.random(16).reshape(4,4)
input

array([[0.97590507, 0.30740538, 0.68739551, 0.26278858],
       [0.19014576, 0.15334457, 0.97410229, 0.22261541],
       [0.92583572, 0.05244915, 0.95115997, 0.80964976],
       [0.77616377, 0.21988717, 0.27275726, 0.89007109]])

가중치 커널 생성

In [30]:
w = np.random.random(4).reshape(2,2)
w

array([[0.64400722, 0.506472  ],
       [0.91813639, 0.22772278]])

합성곱 신경망의 연산은 커널을 플립하지 않은 연산, cross-corelation 을 더 많이 사용한다.

동일한 두 크기의 행렬의 원소 곱으로 계산할 수 있을 것

In [31]:
result_arr = []

for matrix_row in range(input.shape[0]-w.shape[0]+1):
  for matrix_col in range(input.shape[1]-w.shape[1]+1):
    result = []
    for w_row in range(w.shape[0]):
      for w_col in range(w.shape[1]):
        result.append(input[matrix_row+w_row,matrix_col+w_col] * w[w_row, w_col])
    result_arr.append(np.sum(result))

In [32]:
result_arr = []
stride_row = 2
stride_col = 2

for matrix_row in range(0, input.shape[0]-w.shape[0]+1, stride_row):
  for matrix_col in range(0, input.shape[1]-w.shape[1]+1, stride_col):
    print(matrix_row, matrix_col)
    result = []
    for w_row in range(w.shape[0]):
      for w_col in range(w.shape[1]):
        result.append(input[matrix_row+w_row,matrix_col+w_col] * w[w_row, w_col])
    result_arr.append(np.sum(result))

0 0
0 2
2 0
2 2


In [33]:
result_arr

[0.9936819252205649,
 1.5208360953237963,
 1.3855064366261072,
 1.4757366500760771]

In [35]:
result = np.array(result_arr).reshape(int(input.shape[0]-w.shape[0]+1/2),-1)
result

array([[0.99368193, 1.5208361 ],
       [1.38550644, 1.47573665]])