In [2]:
import numpy as np

입력 데이터 생성

In [3]:
input = np.random.random(16).reshape(4,4)
input

array([[0.8383069 , 0.05095063, 0.62240076, 0.99743712],
       [0.7950964 , 0.36897637, 0.79920073, 0.7719454 ],
       [0.25481215, 0.75443591, 0.31732551, 0.48430807],
       [0.54374886, 0.04103307, 0.72146801, 0.45896012]])

가중치 커널 생성

In [4]:
w = np.random.random(4).reshape(2,2)
w

array([[0.89125996, 0.20312673],
       [0.35766807, 0.67890267]])

합성곱 신경망의 연산은 커널을 플립하지 않은 연산, cross-corelation 을 더 많이 사용한다.

동일한 두 크기의 행렬의 원소 곱으로 계산할 수 있을 것

In [5]:
row = []
matrix = []

for matrix_row in range(input.shape[0]-w.shape[0]+1):
  for matrix_col in range(input.shape[1]-w.shape[1]+1):
    matrix = []
    for w_row in range(w.shape[0]):
      row = []
      for w_col in range(w.shape[1]):
        row.append(input[matrix_row+w_row,matrix_col+w_col])
      matrix.append(row)
    print(matrix) 

[[0.8383068999234274, 0.050950629737907205], [0.7950964027818136, 0.36897637443350595]]
[[0.050950629737907205, 0.6224007586217254], [0.36897637443350595, 0.7992007346961458]]
[[0.6224007586217254, 0.997437115337103], [0.7992007346961458, 0.7719454003358299]]
[[0.7950964027818136, 0.36897637443350595], [0.25481214582195166, 0.7544359073522622]]
[[0.36897637443350595, 0.7992007346961458], [0.7544359073522622, 0.3173255060826262]]
[[0.7992007346961458, 0.7719454003358299], [0.3173255060826262, 0.48430807439035384]]
[[0.25481214582195166, 0.7544359073522622], [0.5437488556279283, 0.041033074917227186]]
[[0.7544359073522622, 0.3173255060826262], [0.041033074917227186, 0.7214680085041209]]
[[0.3173255060826262, 0.48430807439035384], [0.7214680085041209, 0.4589601195831766]]


In [6]:
row = []
matrix = []
result = []

for matrix_row in range(input.shape[0]-w.shape[0]+1):
  for matrix_col in range(input.shape[1]-w.shape[1]+1):
    matrix = []
    for w_row in range(w.shape[0]):
      row = []
      for w_col in range(w.shape[1]):
        row.append(input[matrix_row+w_row,matrix_col+w_col])
      matrix.append(row)
    result.append(matrix*w)

result

[array([[0.74714937, 0.01034944],
        [0.28438059, 0.25049905]]), array([[0.04541026, 0.12642623],
        [0.13197107, 0.54257952]]), array([[0.55472087, 0.20260614],
        [0.28584858, 0.5240758 ]]), array([[0.70863759, 0.07494897],
        [0.09113817, 0.51218856]]), array([[0.32885387, 0.16233903],
        [0.26983763, 0.21543313]]), array([[0.71229561, 0.15680275],
        [0.1134972 , 0.32879805]]), array([[0.22710386, 0.1532461 ],
        [0.1944816 , 0.02785746]]), array([[0.67239852, 0.06445729],
        [0.01467622, 0.48980656]]), array([[0.28281952, 0.09837592],
        [0.25804607, 0.31158925]])]

In [7]:
result_arr = []

for matrix_row in range(input.shape[0]-w.shape[0]+1):
  for matrix_col in range(input.shape[1]-w.shape[1]+1):
    result = []
    for w_row in range(w.shape[0]):
      for w_col in range(w.shape[1]):
        result.append(input[matrix_row+w_row,matrix_col+w_col] * w[w_row, w_col])
    result_arr.append(np.sum(result))

In [8]:
result_arr

[1.2923784479200464,
 0.8463870717242483,
 1.5672513956508278,
 1.386913275927562,
 0.9764636694295643,
 1.3113936090233551,
 0.6026890298855487,
 1.2413385908927124,
 0.9508307543272523]

In [9]:
result = np.array(result_arr).reshape(input.shape[0]-w.shape[0]+1,-1)
result

array([[1.29237845, 0.84638707, 1.5672514 ],
       [1.38691328, 0.97646367, 1.31139361],
       [0.60268903, 1.24133859, 0.95083075]])

패딩

In [10]:
padding_matrix = np.zeros((input.shape[0]+w.shape[0]-1, input.shape[1]+w.shape[1]-1))
padding_matrix

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
input

array([[0.8383069 , 0.05095063, 0.62240076, 0.99743712],
       [0.7950964 , 0.36897637, 0.79920073, 0.7719454 ],
       [0.25481215, 0.75443591, 0.31732551, 0.48430807],
       [0.54374886, 0.04103307, 0.72146801, 0.45896012]])

In [15]:
for i in range(input.shape[0]):
  for j in range(input.shape[1]):
    padding_matrix[i+1][j+1] = input[i][j]

In [16]:
padding_matrix

array([[0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.8383069 , 0.05095063, 0.62240076, 0.99743712],
       [0.        , 0.7950964 , 0.36897637, 0.79920073, 0.7719454 ],
       [0.        , 0.25481215, 0.75443591, 0.31732551, 0.48430807],
       [0.        , 0.54374886, 0.04103307, 0.72146801, 0.45896012]])