In [24]:
from sklearn import datasets
raw_iris = datasets.load_iris()

In [25]:
X = raw_iris.data
y = raw_iris.target

In [26]:
import numpy as np

In [27]:
# 각 특성별 평균
x_mean = np.mean(X, axis=0)
x_mean

array([5.84333333, 3.05733333, 3.758     , 1.19933333])

In [28]:
from sklearn import datasets
raw_iris = datasets.load_iris()

In [29]:
X = raw_iris.data
y = raw_iris.target

In [30]:
np.mean(X, axis=0)

array([5.84333333, 3.05733333, 3.758     , 1.19933333])

In [31]:
np.var(X, axis=0)

array([0.68112222, 0.18871289, 3.09550267, 0.57713289])

In [32]:
def standardization(X):
  """
  표준화 함수
  Arg:
    X : 표준화할 데이터
  Return : 
    표준화 후 데이터
  """
  mean = np.mean(X, axis=0)
  std = np.std(X, axis=0)

  return (X-mean)/std

In [33]:
x_std = standardization(X)

In [34]:
np.mean(x_std)

-1.4684549872375404e-15

In [35]:
np.var(x_std)

1.0

In [37]:
class standardization:
  mean = 0
  std = 0

  def __init__(self):
    self.mean = 0
    self.std = 0

  def standardization(self, X):
    """
    표준화 함수
    Arg:
      X : 표준화할 데이터
    Return : 
      표준화 후 데이터
    """
    self.mean = np.mean(X, axis=0)
    self.std = np.std(X, axis=0)

    return (X-self.mean)/self.std

  def transform(self, X):
    return (X-self.mean)/self.std

In [41]:
std = standardization()

std_x = std.standardization(X)
std_x

array([[-9.00681170e-01,  1.01900435e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00, -1.31979479e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.38535265e+00,  3.28414053e-01, -1.39706395e+00,
        -1.31544430e+00],
       [-1.50652052e+00,  9.82172869e-02, -1.28338910e+00,
        -1.31544430e+00],
       [-1.02184904e+00,  1.24920112e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-5.37177559e-01,  1.93979142e+00, -1.16971425e+00,
        -1.05217993e+00],
       [-1.50652052e+00,  7.88807586e-01, -1.34022653e+00,
        -1.18381211e+00],
       [-1.02184904e+00,  7.88807586e-01, -1.28338910e+00,
        -1.31544430e+00],
       [-1.74885626e+00, -3.62176246e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00,  9.82172869e-02, -1.28338910e+00,
        -1.44707648e+00],
       [-5.37177559e-01,  1.47939788e+00, -1.28338910e+00,
        -1.31544430e+00],
       [-1.26418478e+00,  7.88807586e-01, -1.22655167e+00,
      

In [42]:
np.mean(std_x)

-1.4684549872375404e-15

In [43]:
np.var(std_x)

1.0