In [18]:
import numpy as np

입력 데이터 생성

In [19]:
input = np.random.random(16).reshape(4,4)
input

array([[0.08794436, 0.91782939, 0.42781017, 0.78359012],
       [0.89215971, 0.48278037, 0.06832524, 0.85638935],
       [0.38328626, 0.5937976 , 0.96358295, 0.89101867],
       [0.63568914, 0.34415864, 0.65291522, 0.78187485]])

가중치 커널 생성

In [20]:
w = np.random.random(4).reshape(2,2)
w

array([[0.98888509, 0.85977637],
       [0.62117053, 0.92332707]])

합성곱 신경망의 연산은 커널을 플립하지 않은 연산, cross-corelation 을 더 많이 사용한다.

동일한 두 크기의 행렬의 원소 곱으로 계산할 수 있을 것

In [21]:
row = []
matrix = []

for matrix_row in range(input.shape[0]-w.shape[0]+1):
  for matrix_col in range(input.shape[1]-w.shape[1]+1):
    matrix = []
    for w_row in range(w.shape[0]):
      row = []
      for w_col in range(w.shape[1]):
        row.append(input[matrix_row+w_row,matrix_col+w_col])
      matrix.append(row)
    print(matrix) 

[[0.08794435949106072, 0.9178293902430296], [0.8921597075033024, 0.4827803749965519]]
[[0.9178293902430296, 0.4278101747670303], [0.4827803749965519, 0.06832524035761711]]
[[0.4278101747670303, 0.7835901215728238], [0.06832524035761711, 0.8563893450969843]]
[[0.8921597075033024, 0.4827803749965519], [0.3832862613887482, 0.593797604592225]]
[[0.4827803749965519, 0.06832524035761711], [0.593797604592225, 0.9635829510402968]]
[[0.06832524035761711, 0.8563893450969843], [0.9635829510402968, 0.8910186683098356]]
[[0.3832862613887482, 0.593797604592225], [0.6356891403292467, 0.34415864378772687]]
[[0.593797604592225, 0.9635829510402968], [0.34415864378772687, 0.6529152211228911]]
[[0.9635829510402968, 0.8910186683098356], [0.6529152211228911, 0.7818748488517875]]


In [25]:
row = []
matrix = []
result = []

for matrix_row in range(input.shape[0]-w.shape[0]+1):
  for matrix_col in range(input.shape[1]-w.shape[1]+1):
    matrix = []
    for w_row in range(w.shape[0]):
      row = []
      for w_col in range(w.shape[1]):
        row.append(input[matrix_row+w_row,matrix_col+w_col])
      matrix.append(row)
    result.append(matrix*w)

result

[array([[0.08696687, 0.78912802],
        [0.55418332, 0.44576419]]), array([[0.9076278 , 0.36782108],
        [0.29988894, 0.06308654]]), array([[0.4230551 , 0.67371227],
        [0.04244163, 0.79072746]]), array([[0.88224343, 0.41508316],
        [0.23808613, 0.5482694 ]]), array([[0.47741432, 0.05874443],
        [0.36884957, 0.88970222]]), array([[0.06756581, 0.73630332],
        [0.59854934, 0.82270165]]), array([[0.37902607, 0.51053315],
        [0.39487136, 0.31777099]]), array([[0.5871976 , 0.82846585],
        [0.21378121, 0.6028543 ]]), array([[0.95287281, 0.76607679],
        [0.4055717 , 0.72192621]])]

In [31]:
result_arr = []

for matrix_row in range(input.shape[0]-w.shape[0]+1):
  for matrix_col in range(input.shape[1]-w.shape[1]+1):
    result = []
    for w_row in range(w.shape[0]):
      for w_col in range(w.shape[1]):
        result.append(input[matrix_row+w_row,matrix_col+w_col] * w[w_row, w_col])
    result_arr.append(np.sum(result))

In [32]:
result_arr

[1.8760423945638465,
 1.6384243652554065,
 1.9299364610860785,
 2.083682123609485,
 1.7947105381568158,
 2.225120122119695,
 1.6022015709429518,
 2.2322989528570516,
 2.8464475164067666]

In [44]:
result = np.array(result_arr).reshape(input.shape[0]-w.shape[0]+1,-1)
result

array([[1.87604239, 1.63842437, 1.92993646],
       [2.08368212, 1.79471054, 2.22512012],
       [1.60220157, 2.23229895, 2.84644752]])